version: '3.8'

services:
  pi-control-hub: 
    image: josephp97/pi_control_hub_dev:humble
    working_dir: /root/ros_ws
    privileged: true
    volumes:
      - ./Config:/root/config
      - ./Code/ros_ws:/root/ros_ws
    tty: true