################################# PUMP ##########################################
pump:
  client_id: 'pump'
  topic: '/pflanzenkisterl/controllers/pump'
  update_rate: 30
  pwm:
    enabled: 0
  gpios: [
          17
         ]
  on_interval: [
        '8:00:00',
        '11:00:00',
        '14:00:00',
        '17:00:00',
        '20:00:00',
        '23:00:00'
      ]
  off_interval: [
        '8:10:00',
        '11:10:00',
        '14:10:00',
        '17:10:00',
        '20:10:00',
        '23:10:00'
      ]
################################# LEDS ###########################################
leds:
  client_id: 'leds'
  topic: '/pflanzenkisterl/controllers/leds'
  update_rate: 30
  pwm:
    enabled: 0
    dutyCycle: 0.5
    frequency: 500
  gpios: [
          12,
          13,
          18,
          16,
          26
        ]
  on_interval: [
        '8:00:00',
        '18:30:00',
      ]
  off_interval: [
        '12:00:00',
        '20:00:00'
      ]
