#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'gpio-conf==0.0.0','console_scripts','gpio_conf_node'
__requires__ = 'gpio-conf==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('gpio-conf==0.0.0', 'console_scripts', 'gpio_conf_node')()
    )
