#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'time-schedule==0.0.0','console_scripts','time_schedule_node'
__requires__ = 'time-schedule==0.0.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('time-schedule==0.0.0', 'console_scripts', 'time_schedule_node')()
    )
